In [2]:
#Load Libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import RFE
from sklearn.linear_model import Lasso
from sklearn.decomposition import PCA
import plotly.express as px
from collections import Counter
import collections
import math
from tabulate import tabulate

In [3]:
# Read in all dataframes
invitees_df = pd.read_csv(r"C:\Users\mrice\OneDrive\Documents\Data Science - Callum\Projects\Sports Projects\golf_data_engineering_pipeline\masters_players_2025.csv")
masters_results_df = pd.read_csv(r"C:\Users\mrice\OneDrive\Documents\Data Science - Callum\Projects\Sports Projects\golf_data_engineering_pipeline\masters_results.csv")
player_stats_df = pd.read_csv(r"C:\Users\mrice\OneDrive\Documents\Data Science - Callum\Projects\Sports Projects\golf_data_engineering_pipeline\player_stats.csv")
wins_df = pd.read_csv(r"C:\Users\mrice\OneDrive\Documents\Data Science - Callum\Projects\Sports Projects\golf_data_engineering_pipeline\wins.csv")
player_stats_df = player_stats_df.merge(wins_df, how='left', on=['player_name', 'year'])

In [4]:
# Building datasets
full_df = player_stats_df.merge(masters_results_df, how='left', on = ['player_id', 'player_name', 'year'])
full_df = full_df.rename(columns={'position': 'masters_finish'})
# Training data is from 2024 and earlier
train_df = full_df.loc[full_df['year'] <= 2024]
# Prediciting for this year's results is 2024/2025 season
data_2025 = full_df.loc[full_df['year'] >= 2024]
# Prediction dataset is merged with the field of this years competition
prediction_data = invitees_df.merge(data_2025, how='left', on='player_name')
prediction_data.drop(columns=['country', 'masters_finish'], inplace=True)

In [5]:
print(tabulate(train_df, headers='keys', tablefmt='pretty', showindex=False))

+-----------+---------------------------+------+-----------+-------------+-----------+------------+-------+------------+------------+------------+-----------------+----------+----------------+--------------------+--------------------+-------------------+---------------------+--------------------+--------+--------------------+----------------+
| player_id |        player_name        | year | avg_score | bounce_back | drive_acc | drive_dist |  gir  | par3_score | par4_score | par5_score | putts_per_round | scramble | strokes_gained | strokes_gained_arg | strokes_gained_atg | strokes_gained_ot | strokes_gained_putt | strokes_gained_ttg | top_10 | 1st_place_finishes | masters_finish |
+-----------+---------------------------+------+-----------+-------------+-----------+------------+-------+------------+------------+------------+-----------------+----------+----------------+--------------------+--------------------+-------------------+---------------------+--------------------+--------+--------------------+----------------+
|   1024    |       Billy Andrade       | 2005 |  71.011   |    17.96    |   63.38   |   282.0    | 63.92 |    3.13    |    4.06    |    4.58    |      28.71      |   57.7   |     0.385      |       -0.063       |        0.12        |       0.031       |        0.298        |       0.088        |  1.0   |        0.0         |      nan       |
|   1024    |       Billy Andrade       | 2006 |  70.922   |    18.36    |   62.84   |   285.6    | 66.44 |    3.06    |    4.05    |    4.71    |      29.31      |  58.84   |     0.053      |       0.255        |       0.348        |      -0.301       |       -0.248        |       0.302        |  3.0   |        0.0         |      nan       |
|   1024    |       Billy Andrade       | 2007 |  71.588   |    18.33    |   59.56   |   286.2    | 65.03 |    3.11    |    4.1     |    4.68    |      29.75      |  52.35   |     -0.241     |       -0.079       |       0.244        |      -0.272       |       -0.134        |       -0.107       |  nan   |        nan         |      nan       |
|   1024    |       Billy Andrade       | 2008 |  71.967   |    15.02    |   59.35   |   283.3    | 63.52 |    3.1     |    4.12    |    4.83    |      29.93      |  54.09   |     -0.963     |       -0.162       |       -0.11        |      -0.381       |       -0.311        |       -0.653       |  nan   |        nan         |      nan       |
|   1024    |       Billy Andrade       | 2013 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |      nan       |
|   1035    |     Tommy Armour III      | 2005 |  70.968   |    18.09    |   66.06   |   287.1    | 68.18 |    3.07    |    4.05    |    4.7     |      29.77      |  57.12   |     0.283      |       -0.117       |       0.378        |       0.268       |       -0.246        |       0.529        |  1.0   |        0.0         |      nan       |
|   1035    |     Tommy Armour III      | 2006 |  71.343   |    19.9     |   66.74   |   282.4    | 63.76 |    3.0     |    4.09    |    4.79    |      29.08      |  53.77   |     -0.208     |       -0.453       |       -0.08        |       0.195       |        0.13         |       -0.338       |  nan   |        nan         |      nan       |
|   1035    |     Tommy Armour III      | 2007 |  71.133   |    18.27    |   70.17   |   285.7    | 69.84 |    3.02    |    4.03    |    4.76    |      29.86      |  55.74   |     0.157      |       -0.279       |       0.084        |       0.333       |        0.019        |       0.138        |  2.0   |        0.0         |      nan       |
|   1035    |     Tommy Armour III      | 2008 |  70.856   |    16.38    |   63.35   |   287.7    | 66.51 |    3.09    |    4.07    |    4.63    |      29.49      |  55.91   |     -0.124     |       -0.187       |       0.015        |       0.029       |        0.018        |       -0.142       |  5.0   |        0.0         |      nan       |
|   1035    |     Tommy Armour III      | 2009 |  71.227   |    15.53    |   68.61   |   287.3    | 67.05 |    3.14    |    4.03    |    4.72    |      29.48      |   56.4   |     0.079      |       -0.338       |       0.264        |       0.353       |        -0.2         |       0.279        |  1.0   |        0.0         |      nan       |
|   1042    |       Paul Azinger        | 2005 |  71.806   |    20.18    |   60.8    |   284.6    | 60.94 |    3.14    |    4.07    |    4.75    |      28.59      |  55.82   |     -0.209     |       0.268        |       -0.267       |      -0.336       |        0.126        |       -0.335       |  nan   |        nan         |      nan       |
|   1042    |       Paul Azinger        | 2006 |   71.09   |    15.52    |   62.65   |   285.8    | 62.39 |    3.09    |    4.05    |    4.67    |      28.38      |  63.16   |     0.172      |       0.302        |       -0.125       |       -0.32       |        0.315        |       -0.143       |  1.0   |        0.0         |      nan       |
|   1116    |      Michael Bradley      | 2009 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        1.0         |      nan       |
|   1116    |      Michael Bradley      | 2010 |  71.498   |    18.56    |   60.37   |   281.5    | 68.65 |    3.01    |    4.03    |    4.73    |      29.62      |  59.47   |     -0.392     |       0.147        |       0.219        |      -0.676       |       -0.082        |       -0.31        |  nan   |        nan         |      nan       |
|   1116    |      Michael Bradley      | 2011 |  70.877   |    14.56    |   57.03   |   290.7    | 67.62 |    3.01    |    4.06    |    4.71    |      29.71      |  51.72   |     -0.086     |       0.234        |       0.448        |      -0.572       |       -0.196        |        0.11        |  1.0   |        1.0         |      nan       |
|   1116    |      Michael Bradley      | 2012 |  72.059   |    13.57    |   51.88   |   284.5    | 65.35 |    3.06    |    4.09    |    4.78    |      29.78      |   53.8   |     -0.954     |       -0.01        |       0.391        |      -1.146       |       -0.189        |       -0.765       |  nan   |        nan         |      nan       |
|   1116    |      Michael Bradley      | 2013 |  72.345   |    16.57    |   55.46   |   285.3    | 66.13 |    3.02    |    4.15    |    4.75    |      30.17      |   53.0   |     -1.319     |       -0.068       |       0.257        |      -1.058       |        -0.45        |       -0.869       |  nan   |        nan         |      nan       |
|   1127    |       Danny Briggs        | 2005 |  72.244   |    14.81    |   67.86   |   276.1    | 63.89 |    3.08    |    4.13    |    4.73    |      29.72      |  55.43   |     -0.772     |       0.009        |       -0.407       |      -0.229       |       -0.146        |       -0.626       |  1.0   |        0.0         |      nan       |
|   1132    |        Mark Brooks        | 2005 |  72.514   |    14.85    |   67.9    |   269.1    | 59.72 |    3.07    |    4.11    |    4.82    |      28.9       |  58.43   |     -1.235     |       0.226        |       -0.733       |      -0.372       |       -0.357        |       -0.879       |  1.0   |        0.0         |      nan       |
|   1132    |        Mark Brooks        | 2006 |  72.158   |    15.27    |   69.35   |   274.3    | 62.92 |    3.08    |    4.09    |    4.81    |      29.27      |  57.41   |     -0.844     |       0.207        |       -0.243       |       -0.3        |       -0.508        |       -0.335       |  nan   |        nan         |      nan       |
|   1132    |        Mark Brooks        | 2007 |  71.783   |    12.68    |   72.81   |   275.2    | 64.85 |    3.05    |    4.08    |    4.82    |      29.84      |  60.32   |     -0.712     |       0.193        |       -0.566       |      -0.128       |       -0.211        |        -0.5        |  nan   |        nan         |      nan       |
|   1132    |        Mark Brooks        | 2009 |  71.606   |    21.85    |   70.86   |   269.2    | 63.95 |    2.97    |    4.08    |    4.78    |      28.89      |  63.93   |     -0.767     |       -0.004       |       -0.277       |       -0.49       |        0.003        |       -0.771       |  1.0   |        0.0         |      nan       |
|   1139    |        Olin Browne        | 2005 |  70.691   |    19.83    |   73.46   |   278.9    | 69.12 |    3.02    |    4.0     |    4.73    |      29.23      |  59.09   |     0.497      |       -0.16        |       0.407        |      -0.105       |        0.354        |       0.143        |  2.0   |        1.0         |      nan       |
|   1139    |        Olin Browne        | 2006 |  71.117   |    23.68    |   73.56   |   276.6    | 64.32 |    3.04    |    4.08    |    4.73    |      28.86      |  55.09   |     0.253      |       -0.048       |       0.072        |       -0.02       |        0.248        |       0.005        |  2.0   |        0.0         |       45       |
|   1139    |        Olin Browne        | 2007 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |      nan       |
|   1139    |        Olin Browne        | 2008 |  71.584   |    13.39    |   80.42   |   272.1    | 65.63 |    3.04    |    4.11    |    4.84    |      29.99      |  56.47   |     -0.807     |       -0.224       |       -0.243       |       0.081       |       -0.422        |       -0.386       |  nan   |        nan         |      nan       |
|   1142    |        Bart Bryant        | 2005 |  70.187   |    20.25    |   73.0    |   283.2    | 68.93 |    3.0     |    4.03    |    4.62    |      29.53      |  56.58   |      1.07      |       -0.12        |       0.452        |       0.44        |        0.298        |       0.772        |  4.0   |        2.0         |      nan       |
|   1142    |        Bart Bryant        | 2006 |  70.745   |    20.85    |   72.76   |   282.2    | 68.67 |    3.1     |    4.05    |    4.72    |      30.06      |  55.46   |     0.395      |       -0.145       |       0.379        |       0.299       |       -0.138        |       0.533        |  2.0   |        0.0         |      CUT       |
|   1142    |        Bart Bryant        | 2007 |  70.637   |    21.34    |   70.66   |   281.1    | 66.34 |    3.06    |    4.04    |    4.68    |      29.24      |  58.93   |     0.638      |       0.008        |       0.253        |       0.18        |        0.198        |        0.44        |  2.0   |        0.0         |      CUT       |
|   1142    |        Bart Bryant        | 2008 |  70.205   |    18.3     |   73.87   |   279.5    | 64.88 |    3.08    |    4.08    |    4.73    |      29.47      |  59.18   |     0.689      |        0.03        |       0.347        |       0.316       |       -0.004        |       0.693        |  2.0   |        0.0         |      nan       |
|   1142    |        Bart Bryant        | 2009 |  71.177   |    17.42    |   71.9    |   274.6    | 62.76 |    3.06    |    4.09    |    4.73    |      29.24      |  55.25   |     -0.507     |       -0.226       |       -0.033       |      -0.106       |       -0.142        |       -0.365       |  1.0   |        0.0         |      nan       |
|   1157    |         Tom Byrum         | 2005 |  71.268   |    17.34    |   70.28   |   274.3    | 64.93 |    3.03    |    4.09    |    4.72    |      29.47      |  58.02   |     -0.153     |       -0.123       |       0.073        |      -0.255       |        0.151        |       -0.305       |  nan   |        nan         |      nan       |
|   1157    |         Tom Byrum         | 2007 |  72.018   |    15.79    |   71.75   |   281.4    | 65.16 |    3.13    |    4.11    |    4.74    |      30.0       |  57.14   |     -0.842     |       -0.313       |       -0.175       |      -0.278       |       -0.077        |       -0.765       |  nan   |        nan         |      nan       |
|   1161    |     Mark Calcavecchia     | 2005 |   70.49   |    18.63    |   66.51   |   289.3    | 65.86 |    3.07    |    4.04    |    4.64    |      29.16      |  57.32   |     0.718      |       -0.204       |       0.586        |       0.348       |       -0.012        |        0.73        |  5.0   |        1.0         |      nan       |
|   1161    |     Mark Calcavecchia     | 2006 |   71.63   |    16.83    |   65.3    |   282.4    | 62.07 |    3.13    |    4.11    |    4.72    |      29.37      |  56.22   |     -0.136     |       -0.056       |       0.324        |      -0.129       |       -0.276        |       0.139        |  1.0   |        0.0         |      CUT       |
|   1161    |     Mark Calcavecchia     | 2007 |  70.579   |    21.18    |   65.09   |   290.2    | 64.11 |    3.16    |    4.07    |    4.57    |      29.0       |  56.35   |     0.504      |       0.107        |       0.333        |       0.277       |       -0.213        |       0.717        |  6.0   |        1.0         |      T20       |
|   1161    |     Mark Calcavecchia     | 2008 |  71.285   |    18.18    |   65.44   |   283.1    | 64.39 |    3.16    |    4.09    |    4.74    |      29.61      |  54.37   |     0.067      |       -0.163       |       0.513        |       0.247       |        -0.53        |       0.597        |  2.0   |        0.0         |      CUT       |
|   1161    |     Mark Calcavecchia     | 2009 |  71.455   |    19.63    |   61.06   |   286.1    | 65.51 |    3.05    |    4.07    |    4.69    |      29.28      |  57.94   |     -0.475     |       -0.051       |       -0.07        |      -0.095       |       -0.259        |       -0.216       |  3.0   |        0.0         |      nan       |
|   1161    |     Mark Calcavecchia     | 2010 |  72.222   |    23.56    |   62.18   |   281.0    | 65.48 |    3.07    |    4.13    |    4.71    |      30.02      |  50.96   |     -0.996     |       -0.311       |       0.363        |      -0.177       |        -0.87        |       -0.126       |  nan   |        nan         |      nan       |
|   1161    |     Mark Calcavecchia     | 2012 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |      nan       |
|   1175    |        Jim Carter         | 2005 |  72.399   |    10.66    |   68.22   |   276.1    | 61.76 |    3.12    |    4.12    |    4.83    |      29.63      |  55.93   |     -1.015     |       0.125        |       -0.294       |      -0.247       |       -0.599        |       -0.417       |  nan   |        nan         |      nan       |
|   1219    |         John Cook         | 2005 |  71.373   |    24.78    |   69.85   |   272.6    | 63.89 |    3.09    |    4.07    |    4.71    |      29.26      |  52.97   |     -0.339     |       -0.17        |       -0.037       |      -0.171       |        0.039        |       -0.378       |  1.0   |        0.0         |      nan       |
|   1219    |         John Cook         | 2006 |  70.935   |    18.68    |   70.65   |   277.0    | 66.33 |    3.05    |    4.05    |    4.75    |      29.31      |  60.59   |     -0.192     |       0.094        |       -0.223       |      -0.243       |        0.18         |       -0.372       |  2.0   |        0.0         |      nan       |
|   1219    |         John Cook         | 2011 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |      nan       |
|   1226    |       Fred Couples        | 2005 |  70.502   |    26.83    |   57.47   |   296.4    | 68.3  |    3.09    |    4.04    |    4.63    |      29.81      |  54.38   |     0.553      |       -0.03        |       0.629        |       0.499       |       -0.546        |       1.098        |  4.0   |        0.0         |      T39       |
|   1226    |       Fred Couples        | 2006 |  70.789   |    15.76    |   54.36   |   301.5    | 65.33 |    3.09    |    4.11    |    4.66    |      30.02      |  55.13   |     0.336      |       -0.072       |        0.08        |       0.543       |       -0.214        |       0.551        |  2.0   |        0.0         |       T3       |
|   1226    |       Fred Couples        | 2008 |  70.758   |    15.82    |   57.49   |   299.6    | 65.46 |    3.12    |    4.07    |    4.6     |      29.48      |  58.18   |     0.762      |       0.154        |       0.218        |       0.347       |        0.043        |       0.718        |  3.0   |        0.0         |      CUT       |
|   1226    |       Fred Couples        | 2009 |  70.664   |    20.48    |   55.91   |   297.5    | 67.08 |    3.08    |    4.04    |    4.63    |      29.39      |   52.5   |     0.468      |       0.157        |       0.348        |       0.304       |       -0.342        |        0.81        |  4.0   |        0.0         |      CUT       |
|   1226    |       Fred Couples        | 2010 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |      nan       |
|   1226    |       Fred Couples        | 2011 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |      T15       |
|   1249    |         John Daly         | 2005 |  71.516   |    19.47    |   49.35   |   310.1    | 62.79 |    3.07    |    4.11    |    4.69    |      29.29      |  52.06   |     -0.351     |       -0.106       |       -0.113       |       0.192       |       -0.324        |       -0.027       |  2.0   |        0.0         |      CUT       |
|   1249    |         John Daly         | 2006 |  72.396   |    20.22    |   52.48   |   307.1    | 60.88 |    3.13    |    4.15    |    4.75    |      29.37      |  52.46   |     -0.637     |       -0.239       |       -0.028       |       0.196       |       -0.566        |       -0.071       |  nan   |        nan         |      CUT       |
|   1249    |         John Daly         | 2007 |  71.927   |    23.58    |   41.86   |   312.9    | 61.3  |    3.13    |    4.16    |    4.67    |      29.58      |  48.91   |     -0.775     |       -0.225       |       -0.142       |      -0.111       |       -0.297        |       -0.478       |  nan   |        nan         |      nan       |
|   1249    |         John Daly         | 2010 |  71.697   |    25.0     |   52.21   |   305.7    | 65.66 |    3.08    |    4.07    |    4.7     |      29.78      |  53.53   |     -0.989     |       -0.298       |       -0.374       |       0.336       |       -0.654        |       -0.335       |  nan   |        nan         |      nan       |

In [6]:
# strip T and reaplce cut with 100
# Use .loc to ensure the operation is on the original DataFrame
train_df.loc[:, 'masters_finish'] = train_df['masters_finish'].str.lstrip("T")
train_df.loc[:, 'masters_finish'] = train_df['masters_finish'].str.replace("CUT", "100")
train_df.loc[:, 'masters_finish'] = train_df['masters_finish'].str.replace("W/D", "100")
train_df.loc[:, 'masters_finish'] = pd.to_numeric(train_df['masters_finish'], errors='coerce')
train_df.loc[:, 'masters_finish'] = train_df['masters_finish'].astype(float)

In [7]:
train_df.loc[:, 'masters_finish'] = train_df['masters_finish'].fillna(100)
train_df.loc[:, 'top_10'] = train_df['top_10'].fillna(0)
train_df.loc[:, '1st_place_finishes'] = train_df['1st_place_finishes'].fillna(0)
print(tabulate(train_df, headers='keys', tablefmt='pretty', showindex=False))

C:\Users\mrice\AppData\Local\Temp\ipykernel_25380\3628564588.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_df.loc[:, 'masters_finish'] = train_df['masters_finish'].fillna(100)

+-----------+---------------------------+------+-----------+-------------+-----------+------------+-------+------------+------------+------------+-----------------+----------+----------------+--------------------+--------------------+-------------------+---------------------+--------------------+--------+--------------------+----------------+
| player_id |        player_name        | year | avg_score | bounce_back | drive_acc | drive_dist |  gir  | par3_score | par4_score | par5_score | putts_per_round | scramble | strokes_gained | strokes_gained_arg | strokes_gained_atg | strokes_gained_ot | strokes_gained_putt | strokes_gained_ttg | top_10 | 1st_place_finishes | masters_finish |
+-----------+---------------------------+------+-----------+-------------+-----------+------------+-------+------------+------------+------------+-----------------+----------+----------------+--------------------+--------------------+-------------------+---------------------+--------------------+--------+--------------------+----------------+
|   1024    |       Billy Andrade       | 2005 |  71.011   |    17.96    |   63.38   |   282.0    | 63.92 |    3.13    |    4.06    |    4.58    |      28.71      |   57.7   |     0.385      |       -0.063       |        0.12        |       0.031       |        0.298        |       0.088        |  1.0   |        0.0         |     100.0      |
|   1024    |       Billy Andrade       | 2006 |  70.922   |    18.36    |   62.84   |   285.6    | 66.44 |    3.06    |    4.05    |    4.71    |      29.31      |  58.84   |     0.053      |       0.255        |       0.348        |      -0.301       |       -0.248        |       0.302        |  3.0   |        0.0         |     100.0      |
|   1024    |       Billy Andrade       | 2007 |  71.588   |    18.33    |   59.56   |   286.2    | 65.03 |    3.11    |    4.1     |    4.68    |      29.75      |  52.35   |     -0.241     |       -0.079       |       0.244        |      -0.272       |       -0.134        |       -0.107       |  0.0   |        0.0         |     100.0      |
|   1024    |       Billy Andrade       | 2008 |  71.967   |    15.02    |   59.35   |   283.3    | 63.52 |    3.1     |    4.12    |    4.83    |      29.93      |  54.09   |     -0.963     |       -0.162       |       -0.11        |      -0.381       |       -0.311        |       -0.653       |  0.0   |        0.0         |     100.0      |
|   1024    |       Billy Andrade       | 2013 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |     100.0      |
|   1035    |     Tommy Armour III      | 2005 |  70.968   |    18.09    |   66.06   |   287.1    | 68.18 |    3.07    |    4.05    |    4.7     |      29.77      |  57.12   |     0.283      |       -0.117       |       0.378        |       0.268       |       -0.246        |       0.529        |  1.0   |        0.0         |     100.0      |
|   1035    |     Tommy Armour III      | 2006 |  71.343   |    19.9     |   66.74   |   282.4    | 63.76 |    3.0     |    4.09    |    4.79    |      29.08      |  53.77   |     -0.208     |       -0.453       |       -0.08        |       0.195       |        0.13         |       -0.338       |  0.0   |        0.0         |     100.0      |
|   1035    |     Tommy Armour III      | 2007 |  71.133   |    18.27    |   70.17   |   285.7    | 69.84 |    3.02    |    4.03    |    4.76    |      29.86      |  55.74   |     0.157      |       -0.279       |       0.084        |       0.333       |        0.019        |       0.138        |  2.0   |        0.0         |     100.0      |
|   1035    |     Tommy Armour III      | 2008 |  70.856   |    16.38    |   63.35   |   287.7    | 66.51 |    3.09    |    4.07    |    4.63    |      29.49      |  55.91   |     -0.124     |       -0.187       |       0.015        |       0.029       |        0.018        |       -0.142       |  5.0   |        0.0         |     100.0      |
|   1035    |     Tommy Armour III      | 2009 |  71.227   |    15.53    |   68.61   |   287.3    | 67.05 |    3.14    |    4.03    |    4.72    |      29.48      |   56.4   |     0.079      |       -0.338       |       0.264        |       0.353       |        -0.2         |       0.279        |  1.0   |        0.0         |     100.0      |
|   1042    |       Paul Azinger        | 2005 |  71.806   |    20.18    |   60.8    |   284.6    | 60.94 |    3.14    |    4.07    |    4.75    |      28.59      |  55.82   |     -0.209     |       0.268        |       -0.267       |      -0.336       |        0.126        |       -0.335       |  0.0   |        0.0         |     100.0      |
|   1042    |       Paul Azinger        | 2006 |   71.09   |    15.52    |   62.65   |   285.8    | 62.39 |    3.09    |    4.05    |    4.67    |      28.38      |  63.16   |     0.172      |       0.302        |       -0.125       |       -0.32       |        0.315        |       -0.143       |  1.0   |        0.0         |     100.0      |
|   1116    |      Michael Bradley      | 2009 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        1.0         |     100.0      |
|   1116    |      Michael Bradley      | 2010 |  71.498   |    18.56    |   60.37   |   281.5    | 68.65 |    3.01    |    4.03    |    4.73    |      29.62      |  59.47   |     -0.392     |       0.147        |       0.219        |      -0.676       |       -0.082        |       -0.31        |  0.0   |        0.0         |     100.0      |
|   1116    |      Michael Bradley      | 2011 |  70.877   |    14.56    |   57.03   |   290.7    | 67.62 |    3.01    |    4.06    |    4.71    |      29.71      |  51.72   |     -0.086     |       0.234        |       0.448        |      -0.572       |       -0.196        |        0.11        |  1.0   |        1.0         |     100.0      |
|   1116    |      Michael Bradley      | 2012 |  72.059   |    13.57    |   51.88   |   284.5    | 65.35 |    3.06    |    4.09    |    4.78    |      29.78      |   53.8   |     -0.954     |       -0.01        |       0.391        |      -1.146       |       -0.189        |       -0.765       |  0.0   |        0.0         |     100.0      |
|   1116    |      Michael Bradley      | 2013 |  72.345   |    16.57    |   55.46   |   285.3    | 66.13 |    3.02    |    4.15    |    4.75    |      30.17      |   53.0   |     -1.319     |       -0.068       |       0.257        |      -1.058       |        -0.45        |       -0.869       |  0.0   |        0.0         |     100.0      |
|   1127    |       Danny Briggs        | 2005 |  72.244   |    14.81    |   67.86   |   276.1    | 63.89 |    3.08    |    4.13    |    4.73    |      29.72      |  55.43   |     -0.772     |       0.009        |       -0.407       |      -0.229       |       -0.146        |       -0.626       |  1.0   |        0.0         |     100.0      |
|   1132    |        Mark Brooks        | 2005 |  72.514   |    14.85    |   67.9    |   269.1    | 59.72 |    3.07    |    4.11    |    4.82    |      28.9       |  58.43   |     -1.235     |       0.226        |       -0.733       |      -0.372       |       -0.357        |       -0.879       |  1.0   |        0.0         |     100.0      |
|   1132    |        Mark Brooks        | 2006 |  72.158   |    15.27    |   69.35   |   274.3    | 62.92 |    3.08    |    4.09    |    4.81    |      29.27      |  57.41   |     -0.844     |       0.207        |       -0.243       |       -0.3        |       -0.508        |       -0.335       |  0.0   |        0.0         |     100.0      |
|   1132    |        Mark Brooks        | 2007 |  71.783   |    12.68    |   72.81   |   275.2    | 64.85 |    3.05    |    4.08    |    4.82    |      29.84      |  60.32   |     -0.712     |       0.193        |       -0.566       |      -0.128       |       -0.211        |        -0.5        |  0.0   |        0.0         |     100.0      |
|   1132    |        Mark Brooks        | 2009 |  71.606   |    21.85    |   70.86   |   269.2    | 63.95 |    2.97    |    4.08    |    4.78    |      28.89      |  63.93   |     -0.767     |       -0.004       |       -0.277       |       -0.49       |        0.003        |       -0.771       |  1.0   |        0.0         |     100.0      |
|   1139    |        Olin Browne        | 2005 |  70.691   |    19.83    |   73.46   |   278.9    | 69.12 |    3.02    |    4.0     |    4.73    |      29.23      |  59.09   |     0.497      |       -0.16        |       0.407        |      -0.105       |        0.354        |       0.143        |  2.0   |        1.0         |     100.0      |
|   1139    |        Olin Browne        | 2006 |  71.117   |    23.68    |   73.56   |   276.6    | 64.32 |    3.04    |    4.08    |    4.73    |      28.86      |  55.09   |     0.253      |       -0.048       |       0.072        |       -0.02       |        0.248        |       0.005        |  2.0   |        0.0         |      45.0      |
|   1139    |        Olin Browne        | 2007 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |     100.0      |
|   1139    |        Olin Browne        | 2008 |  71.584   |    13.39    |   80.42   |   272.1    | 65.63 |    3.04    |    4.11    |    4.84    |      29.99      |  56.47   |     -0.807     |       -0.224       |       -0.243       |       0.081       |       -0.422        |       -0.386       |  0.0   |        0.0         |     100.0      |
|   1142    |        Bart Bryant        | 2005 |  70.187   |    20.25    |   73.0    |   283.2    | 68.93 |    3.0     |    4.03    |    4.62    |      29.53      |  56.58   |      1.07      |       -0.12        |       0.452        |       0.44        |        0.298        |       0.772        |  4.0   |        2.0         |     100.0      |
|   1142    |        Bart Bryant        | 2006 |  70.745   |    20.85    |   72.76   |   282.2    | 68.67 |    3.1     |    4.05    |    4.72    |      30.06      |  55.46   |     0.395      |       -0.145       |       0.379        |       0.299       |       -0.138        |       0.533        |  2.0   |        0.0         |     100.0      |
|   1142    |        Bart Bryant        | 2007 |  70.637   |    21.34    |   70.66   |   281.1    | 66.34 |    3.06    |    4.04    |    4.68    |      29.24      |  58.93   |     0.638      |       0.008        |       0.253        |       0.18        |        0.198        |        0.44        |  2.0   |        0.0         |     100.0      |
|   1142    |        Bart Bryant        | 2008 |  70.205   |    18.3     |   73.87   |   279.5    | 64.88 |    3.08    |    4.08    |    4.73    |      29.47      |  59.18   |     0.689      |        0.03        |       0.347        |       0.316       |       -0.004        |       0.693        |  2.0   |        0.0         |     100.0      |
|   1142    |        Bart Bryant        | 2009 |  71.177   |    17.42    |   71.9    |   274.6    | 62.76 |    3.06    |    4.09    |    4.73    |      29.24      |  55.25   |     -0.507     |       -0.226       |       -0.033       |      -0.106       |       -0.142        |       -0.365       |  1.0   |        0.0         |     100.0      |
|   1157    |         Tom Byrum         | 2005 |  71.268   |    17.34    |   70.28   |   274.3    | 64.93 |    3.03    |    4.09    |    4.72    |      29.47      |  58.02   |     -0.153     |       -0.123       |       0.073        |      -0.255       |        0.151        |       -0.305       |  0.0   |        0.0         |     100.0      |
|   1157    |         Tom Byrum         | 2007 |  72.018   |    15.79    |   71.75   |   281.4    | 65.16 |    3.13    |    4.11    |    4.74    |      30.0       |  57.14   |     -0.842     |       -0.313       |       -0.175       |      -0.278       |       -0.077        |       -0.765       |  0.0   |        0.0         |     100.0      |
|   1161    |     Mark Calcavecchia     | 2005 |   70.49   |    18.63    |   66.51   |   289.3    | 65.86 |    3.07    |    4.04    |    4.64    |      29.16      |  57.32   |     0.718      |       -0.204       |       0.586        |       0.348       |       -0.012        |        0.73        |  5.0   |        1.0         |     100.0      |
|   1161    |     Mark Calcavecchia     | 2006 |   71.63   |    16.83    |   65.3    |   282.4    | 62.07 |    3.13    |    4.11    |    4.72    |      29.37      |  56.22   |     -0.136     |       -0.056       |       0.324        |      -0.129       |       -0.276        |       0.139        |  1.0   |        0.0         |     100.0      |
|   1161    |     Mark Calcavecchia     | 2007 |  70.579   |    21.18    |   65.09   |   290.2    | 64.11 |    3.16    |    4.07    |    4.57    |      29.0       |  56.35   |     0.504      |       0.107        |       0.333        |       0.277       |       -0.213        |       0.717        |  6.0   |        1.0         |      20.0      |
|   1161    |     Mark Calcavecchia     | 2008 |  71.285   |    18.18    |   65.44   |   283.1    | 64.39 |    3.16    |    4.09    |    4.74    |      29.61      |  54.37   |     0.067      |       -0.163       |       0.513        |       0.247       |        -0.53        |       0.597        |  2.0   |        0.0         |     100.0      |
|   1161    |     Mark Calcavecchia     | 2009 |  71.455   |    19.63    |   61.06   |   286.1    | 65.51 |    3.05    |    4.07    |    4.69    |      29.28      |  57.94   |     -0.475     |       -0.051       |       -0.07        |      -0.095       |       -0.259        |       -0.216       |  3.0   |        0.0         |     100.0      |
|   1161    |     Mark Calcavecchia     | 2010 |  72.222   |    23.56    |   62.18   |   281.0    | 65.48 |    3.07    |    4.13    |    4.71    |      30.02      |  50.96   |     -0.996     |       -0.311       |       0.363        |      -0.177       |        -0.87        |       -0.126       |  0.0   |        0.0         |     100.0      |
|   1161    |     Mark Calcavecchia     | 2012 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |     100.0      |
|   1175    |        Jim Carter         | 2005 |  72.399   |    10.66    |   68.22   |   276.1    | 61.76 |    3.12    |    4.12    |    4.83    |      29.63      |  55.93   |     -1.015     |       0.125        |       -0.294       |      -0.247       |       -0.599        |       -0.417       |  0.0   |        0.0         |     100.0      |
|   1219    |         John Cook         | 2005 |  71.373   |    24.78    |   69.85   |   272.6    | 63.89 |    3.09    |    4.07    |    4.71    |      29.26      |  52.97   |     -0.339     |       -0.17        |       -0.037       |      -0.171       |        0.039        |       -0.378       |  1.0   |        0.0         |     100.0      |
|   1219    |         John Cook         | 2006 |  70.935   |    18.68    |   70.65   |   277.0    | 66.33 |    3.05    |    4.05    |    4.75    |      29.31      |  60.59   |     -0.192     |       0.094        |       -0.223       |      -0.243       |        0.18         |       -0.372       |  2.0   |        0.0         |     100.0      |
|   1219    |         John Cook         | 2011 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |     100.0      |
|   1226    |       Fred Couples        | 2005 |  70.502   |    26.83    |   57.47   |   296.4    | 68.3  |    3.09    |    4.04    |    4.63    |      29.81      |  54.38   |     0.553      |       -0.03        |       0.629        |       0.499       |       -0.546        |       1.098        |  4.0   |        0.0         |      39.0      |
|   1226    |       Fred Couples        | 2006 |  70.789   |    15.76    |   54.36   |   301.5    | 65.33 |    3.09    |    4.11    |    4.66    |      30.02      |  55.13   |     0.336      |       -0.072       |        0.08        |       0.543       |       -0.214        |       0.551        |  2.0   |        0.0         |      3.0       |
|   1226    |       Fred Couples        | 2008 |  70.758   |    15.82    |   57.49   |   299.6    | 65.46 |    3.12    |    4.07    |    4.6     |      29.48      |  58.18   |     0.762      |       0.154        |       0.218        |       0.347       |        0.043        |       0.718        |  3.0   |        0.0         |     100.0      |
|   1226    |       Fred Couples        | 2009 |  70.664   |    20.48    |   55.91   |   297.5    | 67.08 |    3.08    |    4.04    |    4.63    |      29.39      |   52.5   |     0.468      |       0.157        |       0.348        |       0.304       |       -0.342        |        0.81        |  4.0   |        0.0         |     100.0      |
|   1226    |       Fred Couples        | 2010 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |     100.0      |
|   1226    |       Fred Couples        | 2011 |    nan    |     nan     |    nan    |    nan     |  nan  |    nan     |    nan     |    nan     |       nan       |   nan    |      nan       |        nan         |        nan         |        nan        |         nan         |        nan         |  1.0   |        0.0         |      15.0      |
|   1249    |         John Daly         | 2005 |  71.516   |    19.47    |   49.35   |   310.1    | 62.79 |    3.07    |    4.11    |    4.69    |      29.29      |  52.06   |     -0.351     |       -0.106       |       -0.113       |       0.192       |       -0.324        |       -0.027       |  2.0   |        0.0         |     100.0      |
|   1249    |         John Daly         | 2006 |  72.396   |    20.22    |   52.48   |   307.1    | 60.88 |    3.13    |    4.15    |    4.75    |      29.37      |  52.46   |     -0.637     |       -0.239       |       -0.028       |       0.196       |       -0.566        |       -0.071       |  0.0   |        0.0         |     100.0      |
|   1249    |         John Daly         | 2007 |  71.927   |    23.58    |   41.86   |   312.9    | 61.3  |    3.13    |    4.16    |    4.67    |      29.58      |  48.91   |     -0.775     |       -0.225       |       -0.142       |      -0.111       |       -0.297        |       -0.478       |  0.0   |        0.0         |     100.0      |
|   1249    |         John Daly         | 2010 |  71.697   |    25.0     |   52.21   |   305.7    | 65.66 |    3.08    |    4.07    |    4.7     |      29.78      |  53.53   |     -0.989     |       -0.298       |       -0.374       |       0.336       |       -0.654        |       -0.335       |  0.0   |        0.0         |     100.0      |

In [8]:
train_df=train_df.dropna()
print(train_df.shape)

(3798, 22)

In [9]:
def top_10(pos):
    try:
        pos=int(pos)
        if pos <= 10:
            return 1
        else:
            return 0
    except ValueError:
        return 0
    
train_df['top_10_masters'] = train_df['masters_finish'].apply(top_10)

print(train_df[train_df['top_10_masters']==1])

      player_id      player_name  year  avg_score  bounce_back  drive_acc  \
45         1226     Fred Couples  2006     70.789        15.76      54.36
176        1810   Phil Mickelson  2005     69.386        21.28      58.69
177        1810   Phil Mickelson  2006     69.500        23.33      58.61
179        1810   Phil Mickelson  2008     69.167        26.21      55.27
180        1810   Phil Mickelson  2009     70.218        21.28      52.21
...         ...              ...   ...        ...          ...        ...
4357      51634  Sahith Theegala  2023     70.219        24.64      52.85
4404      52372    Cameron Champ  2022     71.527        19.64      57.79
4431      52955     Ludvig Åberg  2024     69.988        21.76      62.38
4510      57366    Cameron Young  2023     70.515        25.11      59.05
4511      57366    Cameron Young  2024     70.841        23.48      59.61

      drive_dist    gir  par3_score  par4_score  ...  strokes_gained  \
45         301.5  65.33        3.09        4.11  ...           0.336
176        300.0  66.89        3.06        3.97  ...           1.525
177        300.7  68.28        3.05        4.00  ...           1.955
179        295.7  65.81        3.09        4.01  ...           1.818
180        300.1  64.29        3.03        4.05  ...           0.816
...          ...    ...         ...         ...  ...             ...
4357       304.9  64.94        3.00        4.00  ...           0.788
4404       321.4  67.16        3.10        4.10  ...          -0.082
4431       310.1  68.15        3.00        3.97  ...           1.064
4510       315.7  68.99        3.01        4.01  ...           0.333
4511       308.9  66.19        3.10        4.01  ...           0.262

      strokes_gained_arg  strokes_gained_atg  strokes_gained_ot  \
45                -0.072               0.080              0.543
176                0.355               0.565              0.341
177                0.136               0.983              0.569
179                0.360               0.842              0.402
180                0.383               0.268              0.312
...                  ...                 ...                ...
4357               0.267               0.175             -0.139
4404              -0.365              -0.178              0.637
4431              -0.008               0.434              0.502
4510              -0.019               0.072              0.581
4511               0.005               0.116              0.375

      strokes_gained_putt  strokes_gained_ttg  top_10  1st_place_finishes  \
45                 -0.214               0.551     2.0                 0.0
176                 0.264               1.261     9.0                 4.0
177                 0.268               1.688     8.0                 2.0
179                 0.214               1.604     8.0                 0.0
180                -0.146               0.963     7.0                 3.0
...                   ...                 ...     ...                 ...
4357                0.485               0.304     8.0                 1.0
4404               -0.177               0.095     2.0                 0.0
4431                0.135               0.929     8.0                 0.0
4510               -0.287               0.620     5.0                 0.0
4511               -0.234               0.496     6.0                 0.0

      masters_finish  top_10_masters
45               3.0               1
176             10.0               1
177              1.0               1
179              5.0               1
180              5.0               1
...              ...             ...
4357             9.0               1
4404            10.0               1
4431             2.0               1
4510             7.0               1
4511             9.0               1

[174 rows x 23 columns]

In [10]:
def winner(x):
    if x == 1:
        win = 1
    else:
        win = 0
    return win

train_df.loc[:, 'masters_win'] = train_df['masters_finish'].apply(winner)
print(tabulate(train_df, headers='keys', tablefmt='pretty', showindex=False))

+-----------+---------------------------+------+-----------+-------------+-----------+------------+-------+------------+------------+------------+-----------------+----------+----------------+--------------------+--------------------+-------------------+---------------------+--------------------+--------+--------------------+----------------+----------------+-------------+
| player_id |        player_name        | year | avg_score | bounce_back | drive_acc | drive_dist |  gir  | par3_score | par4_score | par5_score | putts_per_round | scramble | strokes_gained | strokes_gained_arg | strokes_gained_atg | strokes_gained_ot | strokes_gained_putt | strokes_gained_ttg | top_10 | 1st_place_finishes | masters_finish | top_10_masters | masters_win |
+-----------+---------------------------+------+-----------+-------------+-----------+------------+-------+------------+------------+------------+-----------------+----------+----------------+--------------------+--------------------+-------------------+---------------------+--------------------+--------+--------------------+----------------+----------------+-------------+
|   1024    |       Billy Andrade       | 2005 |  71.011   |    17.96    |   63.38   |   282.0    | 63.92 |    3.13    |    4.06    |    4.58    |      28.71      |   57.7   |     0.385      |       -0.063       |        0.12        |       0.031       |        0.298        |       0.088        |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1024    |       Billy Andrade       | 2006 |  70.922   |    18.36    |   62.84   |   285.6    | 66.44 |    3.06    |    4.05    |    4.71    |      29.31      |  58.84   |     0.053      |       0.255        |       0.348        |      -0.301       |       -0.248        |       0.302        |  3.0   |        0.0         |     100.0      |       0        |      0      |
|   1024    |       Billy Andrade       | 2007 |  71.588   |    18.33    |   59.56   |   286.2    | 65.03 |    3.11    |    4.1     |    4.68    |      29.75      |  52.35   |     -0.241     |       -0.079       |       0.244        |      -0.272       |       -0.134        |       -0.107       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1024    |       Billy Andrade       | 2008 |  71.967   |    15.02    |   59.35   |   283.3    | 63.52 |    3.1     |    4.12    |    4.83    |      29.93      |  54.09   |     -0.963     |       -0.162       |       -0.11        |      -0.381       |       -0.311        |       -0.653       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1035    |     Tommy Armour III      | 2005 |  70.968   |    18.09    |   66.06   |   287.1    | 68.18 |    3.07    |    4.05    |    4.7     |      29.77      |  57.12   |     0.283      |       -0.117       |       0.378        |       0.268       |       -0.246        |       0.529        |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1035    |     Tommy Armour III      | 2006 |  71.343   |    19.9     |   66.74   |   282.4    | 63.76 |    3.0     |    4.09    |    4.79    |      29.08      |  53.77   |     -0.208     |       -0.453       |       -0.08        |       0.195       |        0.13         |       -0.338       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1035    |     Tommy Armour III      | 2007 |  71.133   |    18.27    |   70.17   |   285.7    | 69.84 |    3.02    |    4.03    |    4.76    |      29.86      |  55.74   |     0.157      |       -0.279       |       0.084        |       0.333       |        0.019        |       0.138        |  2.0   |        0.0         |     100.0      |       0        |      0      |
|   1035    |     Tommy Armour III      | 2008 |  70.856   |    16.38    |   63.35   |   287.7    | 66.51 |    3.09    |    4.07    |    4.63    |      29.49      |  55.91   |     -0.124     |       -0.187       |       0.015        |       0.029       |        0.018        |       -0.142       |  5.0   |        0.0         |     100.0      |       0        |      0      |
|   1035    |     Tommy Armour III      | 2009 |  71.227   |    15.53    |   68.61   |   287.3    | 67.05 |    3.14    |    4.03    |    4.72    |      29.48      |   56.4   |     0.079      |       -0.338       |       0.264        |       0.353       |        -0.2         |       0.279        |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1042    |       Paul Azinger        | 2005 |  71.806   |    20.18    |   60.8    |   284.6    | 60.94 |    3.14    |    4.07    |    4.75    |      28.59      |  55.82   |     -0.209     |       0.268        |       -0.267       |      -0.336       |        0.126        |       -0.335       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1042    |       Paul Azinger        | 2006 |   71.09   |    15.52    |   62.65   |   285.8    | 62.39 |    3.09    |    4.05    |    4.67    |      28.38      |  63.16   |     0.172      |       0.302        |       -0.125       |       -0.32       |        0.315        |       -0.143       |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1116    |      Michael Bradley      | 2010 |  71.498   |    18.56    |   60.37   |   281.5    | 68.65 |    3.01    |    4.03    |    4.73    |      29.62      |  59.47   |     -0.392     |       0.147        |       0.219        |      -0.676       |       -0.082        |       -0.31        |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1116    |      Michael Bradley      | 2011 |  70.877   |    14.56    |   57.03   |   290.7    | 67.62 |    3.01    |    4.06    |    4.71    |      29.71      |  51.72   |     -0.086     |       0.234        |       0.448        |      -0.572       |       -0.196        |        0.11        |  1.0   |        1.0         |     100.0      |       0        |      0      |
|   1116    |      Michael Bradley      | 2012 |  72.059   |    13.57    |   51.88   |   284.5    | 65.35 |    3.06    |    4.09    |    4.78    |      29.78      |   53.8   |     -0.954     |       -0.01        |       0.391        |      -1.146       |       -0.189        |       -0.765       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1116    |      Michael Bradley      | 2013 |  72.345   |    16.57    |   55.46   |   285.3    | 66.13 |    3.02    |    4.15    |    4.75    |      30.17      |   53.0   |     -1.319     |       -0.068       |       0.257        |      -1.058       |        -0.45        |       -0.869       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1127    |       Danny Briggs        | 2005 |  72.244   |    14.81    |   67.86   |   276.1    | 63.89 |    3.08    |    4.13    |    4.73    |      29.72      |  55.43   |     -0.772     |       0.009        |       -0.407       |      -0.229       |       -0.146        |       -0.626       |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1132    |        Mark Brooks        | 2005 |  72.514   |    14.85    |   67.9    |   269.1    | 59.72 |    3.07    |    4.11    |    4.82    |      28.9       |  58.43   |     -1.235     |       0.226        |       -0.733       |      -0.372       |       -0.357        |       -0.879       |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1132    |        Mark Brooks        | 2006 |  72.158   |    15.27    |   69.35   |   274.3    | 62.92 |    3.08    |    4.09    |    4.81    |      29.27      |  57.41   |     -0.844     |       0.207        |       -0.243       |       -0.3        |       -0.508        |       -0.335       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1132    |        Mark Brooks        | 2007 |  71.783   |    12.68    |   72.81   |   275.2    | 64.85 |    3.05    |    4.08    |    4.82    |      29.84      |  60.32   |     -0.712     |       0.193        |       -0.566       |      -0.128       |       -0.211        |        -0.5        |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1132    |        Mark Brooks        | 2009 |  71.606   |    21.85    |   70.86   |   269.2    | 63.95 |    2.97    |    4.08    |    4.78    |      28.89      |  63.93   |     -0.767     |       -0.004       |       -0.277       |       -0.49       |        0.003        |       -0.771       |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1139    |        Olin Browne        | 2005 |  70.691   |    19.83    |   73.46   |   278.9    | 69.12 |    3.02    |    4.0     |    4.73    |      29.23      |  59.09   |     0.497      |       -0.16        |       0.407        |      -0.105       |        0.354        |       0.143        |  2.0   |        1.0         |     100.0      |       0        |      0      |
|   1139    |        Olin Browne        | 2006 |  71.117   |    23.68    |   73.56   |   276.6    | 64.32 |    3.04    |    4.08    |    4.73    |      28.86      |  55.09   |     0.253      |       -0.048       |       0.072        |       -0.02       |        0.248        |       0.005        |  2.0   |        0.0         |      45.0      |       0        |      0      |
|   1139    |        Olin Browne        | 2008 |  71.584   |    13.39    |   80.42   |   272.1    | 65.63 |    3.04    |    4.11    |    4.84    |      29.99      |  56.47   |     -0.807     |       -0.224       |       -0.243       |       0.081       |       -0.422        |       -0.386       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1142    |        Bart Bryant        | 2005 |  70.187   |    20.25    |   73.0    |   283.2    | 68.93 |    3.0     |    4.03    |    4.62    |      29.53      |  56.58   |      1.07      |       -0.12        |       0.452        |       0.44        |        0.298        |       0.772        |  4.0   |        2.0         |     100.0      |       0        |      0      |
|   1142    |        Bart Bryant        | 2006 |  70.745   |    20.85    |   72.76   |   282.2    | 68.67 |    3.1     |    4.05    |    4.72    |      30.06      |  55.46   |     0.395      |       -0.145       |       0.379        |       0.299       |       -0.138        |       0.533        |  2.0   |        0.0         |     100.0      |       0        |      0      |
|   1142    |        Bart Bryant        | 2007 |  70.637   |    21.34    |   70.66   |   281.1    | 66.34 |    3.06    |    4.04    |    4.68    |      29.24      |  58.93   |     0.638      |       0.008        |       0.253        |       0.18        |        0.198        |        0.44        |  2.0   |        0.0         |     100.0      |       0        |      0      |
|   1142    |        Bart Bryant        | 2008 |  70.205   |    18.3     |   73.87   |   279.5    | 64.88 |    3.08    |    4.08    |    4.73    |      29.47      |  59.18   |     0.689      |        0.03        |       0.347        |       0.316       |       -0.004        |       0.693        |  2.0   |        0.0         |     100.0      |       0        |      0      |
|   1142    |        Bart Bryant        | 2009 |  71.177   |    17.42    |   71.9    |   274.6    | 62.76 |    3.06    |    4.09    |    4.73    |      29.24      |  55.25   |     -0.507     |       -0.226       |       -0.033       |      -0.106       |       -0.142        |       -0.365       |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1157    |         Tom Byrum         | 2005 |  71.268   |    17.34    |   70.28   |   274.3    | 64.93 |    3.03    |    4.09    |    4.72    |      29.47      |  58.02   |     -0.153     |       -0.123       |       0.073        |      -0.255       |        0.151        |       -0.305       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1157    |         Tom Byrum         | 2007 |  72.018   |    15.79    |   71.75   |   281.4    | 65.16 |    3.13    |    4.11    |    4.74    |      30.0       |  57.14   |     -0.842     |       -0.313       |       -0.175       |      -0.278       |       -0.077        |       -0.765       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1161    |     Mark Calcavecchia     | 2005 |   70.49   |    18.63    |   66.51   |   289.3    | 65.86 |    3.07    |    4.04    |    4.64    |      29.16      |  57.32   |     0.718      |       -0.204       |       0.586        |       0.348       |       -0.012        |        0.73        |  5.0   |        1.0         |     100.0      |       0        |      0      |
|   1161    |     Mark Calcavecchia     | 2006 |   71.63   |    16.83    |   65.3    |   282.4    | 62.07 |    3.13    |    4.11    |    4.72    |      29.37      |  56.22   |     -0.136     |       -0.056       |       0.324        |      -0.129       |       -0.276        |       0.139        |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1161    |     Mark Calcavecchia     | 2007 |  70.579   |    21.18    |   65.09   |   290.2    | 64.11 |    3.16    |    4.07    |    4.57    |      29.0       |  56.35   |     0.504      |       0.107        |       0.333        |       0.277       |       -0.213        |       0.717        |  6.0   |        1.0         |      20.0      |       0        |      0      |
|   1161    |     Mark Calcavecchia     | 2008 |  71.285   |    18.18    |   65.44   |   283.1    | 64.39 |    3.16    |    4.09    |    4.74    |      29.61      |  54.37   |     0.067      |       -0.163       |       0.513        |       0.247       |        -0.53        |       0.597        |  2.0   |        0.0         |     100.0      |       0        |      0      |
|   1161    |     Mark Calcavecchia     | 2009 |  71.455   |    19.63    |   61.06   |   286.1    | 65.51 |    3.05    |    4.07    |    4.69    |      29.28      |  57.94   |     -0.475     |       -0.051       |       -0.07        |      -0.095       |       -0.259        |       -0.216       |  3.0   |        0.0         |     100.0      |       0        |      0      |
|   1161    |     Mark Calcavecchia     | 2010 |  72.222   |    23.56    |   62.18   |   281.0    | 65.48 |    3.07    |    4.13    |    4.71    |      30.02      |  50.96   |     -0.996     |       -0.311       |       0.363        |      -0.177       |        -0.87        |       -0.126       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1175    |        Jim Carter         | 2005 |  72.399   |    10.66    |   68.22   |   276.1    | 61.76 |    3.12    |    4.12    |    4.83    |      29.63      |  55.93   |     -1.015     |       0.125        |       -0.294       |      -0.247       |       -0.599        |       -0.417       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1219    |         John Cook         | 2005 |  71.373   |    24.78    |   69.85   |   272.6    | 63.89 |    3.09    |    4.07    |    4.71    |      29.26      |  52.97   |     -0.339     |       -0.17        |       -0.037       |      -0.171       |        0.039        |       -0.378       |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1219    |         John Cook         | 2006 |  70.935   |    18.68    |   70.65   |   277.0    | 66.33 |    3.05    |    4.05    |    4.75    |      29.31      |  60.59   |     -0.192     |       0.094        |       -0.223       |      -0.243       |        0.18         |       -0.372       |  2.0   |        0.0         |     100.0      |       0        |      0      |
|   1226    |       Fred Couples        | 2005 |  70.502   |    26.83    |   57.47   |   296.4    | 68.3  |    3.09    |    4.04    |    4.63    |      29.81      |  54.38   |     0.553      |       -0.03        |       0.629        |       0.499       |       -0.546        |       1.098        |  4.0   |        0.0         |      39.0      |       0        |      0      |
|   1226    |       Fred Couples        | 2006 |  70.789   |    15.76    |   54.36   |   301.5    | 65.33 |    3.09    |    4.11    |    4.66    |      30.02      |  55.13   |     0.336      |       -0.072       |        0.08        |       0.543       |       -0.214        |       0.551        |  2.0   |        0.0         |      3.0       |       1        |      0      |
|   1226    |       Fred Couples        | 2008 |  70.758   |    15.82    |   57.49   |   299.6    | 65.46 |    3.12    |    4.07    |    4.6     |      29.48      |  58.18   |     0.762      |       0.154        |       0.218        |       0.347       |        0.043        |       0.718        |  3.0   |        0.0         |     100.0      |       0        |      0      |
|   1226    |       Fred Couples        | 2009 |  70.664   |    20.48    |   55.91   |   297.5    | 67.08 |    3.08    |    4.04    |    4.63    |      29.39      |   52.5   |     0.468      |       0.157        |       0.348        |       0.304       |       -0.342        |        0.81        |  4.0   |        0.0         |     100.0      |       0        |      0      |
|   1249    |         John Daly         | 2005 |  71.516   |    19.47    |   49.35   |   310.1    | 62.79 |    3.07    |    4.11    |    4.69    |      29.29      |  52.06   |     -0.351     |       -0.106       |       -0.113       |       0.192       |       -0.324        |       -0.027       |  2.0   |        0.0         |     100.0      |       0        |      0      |
|   1249    |         John Daly         | 2006 |  72.396   |    20.22    |   52.48   |   307.1    | 60.88 |    3.13    |    4.15    |    4.75    |      29.37      |  52.46   |     -0.637     |       -0.239       |       -0.028       |       0.196       |       -0.566        |       -0.071       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1249    |         John Daly         | 2007 |  71.927   |    23.58    |   41.86   |   312.9    | 61.3  |    3.13    |    4.16    |    4.67    |      29.58      |  48.91   |     -0.775     |       -0.225       |       -0.142       |      -0.111       |       -0.297        |       -0.478       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1249    |         John Daly         | 2010 |  71.697   |    25.0     |   52.21   |   305.7    | 65.66 |    3.08    |    4.07    |    4.7     |      29.78      |  53.53   |     -0.989     |       -0.298       |       -0.374       |       0.336       |       -0.654        |       -0.335       |  0.0   |        0.0         |     100.0      |       0        |      0      |
|   1249    |         John Daly         | 2012 |  70.879   |    21.52    |   55.78   |   306.7    | 62.08 |    3.1     |    4.12    |    4.56    |      28.89      |  52.55   |     -0.406     |       -0.604       |       -0.267       |       0.272       |        0.192        |       -0.598       |  1.0   |        0.0         |     100.0      |       0        |      0      |
|   1313    |      Steve Elkington      | 2005 |  70.321   |    16.87    |   65.91   |   283.5    | 67.16 |    3.06    |    4.04    |    4.66    |      29.45      |  60.61   |     0.489      |       0.128        |       -0.033       |       0.143       |        0.251        |       0.238        |  3.0   |        0.0         |     100.0      |       0        |      0      |
|   1313    |      Steve Elkington      | 2006 |  71.088   |    15.97    |   73.91   |   285.8    | 69.61 |    3.08    |    4.04    |    4.64    |      29.88      |  64.52   |     0.028      |       0.213        |       -0.153       |       0.302       |       -0.334        |       0.363        |  0.0   |        0.0         |     100.0      |       0        |      0      |

In [11]:
print(train_df[(train_df['player_name'] == 'Phil Mickelson') & (train_df['year'] == 2010)])
train_df.loc[181, 'masters_win'] = 1

     player_id     player_name  year  avg_score  bounce_back  drive_acc  \
181       1810  Phil Mickelson  2010     69.966         19.7      52.66

     drive_dist    gir  par3_score  par4_score  ...  strokes_gained_arg  \
181       299.1  65.13        3.05        4.01  ...               0.228

     strokes_gained_atg  strokes_gained_ot  strokes_gained_putt  \
181               0.738              0.185               -0.149

     strokes_gained_ttg  top_10  1st_place_finishes  masters_finish  \
181               1.151     6.0                 1.0           100.0

     top_10_masters  masters_win
181               0            0

[1 rows x 24 columns]

In [12]:
# Remove rows where 'year' is 2019 or 2016
train_df = train_df[~train_df['year'].isin([2019, 2016])]

In [13]:
columns = list(train_df.columns.values)
predictors = columns[3:]
predictors.remove('top_10_masters')
predictors.remove('masters_win')
predictors.remove('masters_finish')
predictors.remove('top_10')
predictors.remove('1st_place_finishes')
X = train_df[predictors]
y = train_df['masters_win']

over = SMOTE(sampling_strategy=0.1, k_neighbors=3)
under = RandomUnderSampler(sampling_strategy=1)
steps = [('o', over), ('u', under)]
pipeline = Pipeline(steps=steps)
X_train, y_train = pipeline.fit_resample(X, y)

rfc = RandomForestClassifier()
model = rfc.fit(X_train, y_train)

pd.DataFrame(list(zip(X.columns, model.feature_importances_)), columns=['predictor', 'feature_importace'])

              predictor  feature_importace
0             avg_score           0.261638
1           bounce_back           0.023516
2             drive_acc           0.023480
3            drive_dist           0.041726
4                   gir           0.019736
5            par3_score           0.019847
6            par4_score           0.045292
7            par5_score           0.020155
8       putts_per_round           0.015912
9              scramble           0.022501
10       strokes_gained           0.187940
11   strokes_gained_arg           0.031525
12   strokes_gained_atg           0.111425
13    strokes_gained_ot           0.062713
14  strokes_gained_putt           0.016595
15   strokes_gained_ttg           0.095998

In [14]:
# Random forest no sampling techniques
training = train_df.loc[train_df['year']<=2019]
test = train_df.loc[train_df['year']>2019]
X_train = training[predictors]
y_train = training['top_10_masters']
X_test = test[predictors]
y_test = test['top_10_masters']

rfc = RandomForestClassifier()
model = rfc.fit(X_train, y_train)

y_test_pred = model.predict(X_test)

print('precision:', metrics.precision_score(y_test, y_test_pred))
print('recall:', metrics.recall_score(y_test, y_test_pred))
print('f1:', metrics.f1_score(y_test, y_test_pred))
print('accuarcy:', metrics.accuracy_score(y_test, y_test_pred))

precision: 0.4
recall: 0.15
f1: 0.21818181818181817
accuarcy: 0.955067920585162

In [15]:
# Preicting top 10 with resmapling techniques
training = train_df.loc[train_df['year']<=2019]
testing = train_df.loc[train_df['year']>2019]
X_train = training[predictors]
y_train = training['top_10_masters']
X_test = testing[predictors]
y_test = testing['top_10_masters']

over = SMOTE(sampling_strategy=0.5)
under = RandomUnderSampler(sampling_strategy=0.95)

steps = [('o', over), ('u', under)]
pipeline = Pipeline(steps=steps)

X_train, y_train = pipeline.fit_resample(X_train, y_train)
model = rfc.fit(X_train, y_train)

y_pred = model.predict(X_test)

print('precision:', metrics.precision_score(y_test, y_pred))
print('recall:', metrics.recall_score(y_test, y_pred))
print('f1:', metrics.f1_score(y_test, y_pred))
print('accuarcy:', metrics.accuracy_score(y_test, y_pred))

precision: 0.2736842105263158
recall: 0.65
f1: 0.3851851851851852
accuarcy: 0.9132706374085684

In [16]:
# Best out of box model
training = train_df.loc[train_df['year']<=2019]
testing = train_df.loc[train_df['year']>2019]
X_train = training[predictors]
y_train = training['top_10_masters']
X_test = testing[predictors]
y_test = testing['top_10_masters']

models = {
    'random_forest': RandomForestClassifier(),
    'gradient_boosted': xgb.XGBClassifier(objective='binary:logistic', eval_metric='logloss'),
    'SVC': SVC()
}

over = SMOTE(sampling_strategy=0.5)
under = RandomUnderSampler(sampling_strategy=0.95)

results = {}

for name, model in models.items():
    
    steps = [('o', over), ('u', under), ('model', model)]
    pipeline = Pipeline(steps=steps)

    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    results[name] = {
        'precision': metrics.precision_score(y_test, y_pred),
        'recall': metrics.recall_score(y_test, y_pred),
        'f1': metrics.f1_score(y_test, y_pred),
        'accuracy': metrics.accuracy_score(y_test, y_pred)
    }
    
for name, scores in results.items():
    print(f"{name} Performance:")
    print(f"Precision: {scores['precision']:.4f}")
    print(f"Recall: {scores['recall']:.4f}")
    print(f"F1 Score: {scores['f1']:.4f}")
    print(f"Accuracy: {scores['accuracy']:.4f}")
    print("-" * 50)

random_forest Performance:
Precision: 0.2500
Recall: 0.6500
F1 Score: 0.3611
Accuracy: 0.9039
--------------------------------------------------
gradient_boosted Performance:
Precision: 0.2584
Recall: 0.5750
F1 Score: 0.3566
Accuracy: 0.9133
--------------------------------------------------
SVC Performance:
Precision: 0.0602
Recall: 0.9750
F1 Score: 0.1134
Accuracy: 0.3626
--------------------------------------------------

In [17]:
# Grid search for best params
training = train_df.loc[train_df['year']<=2019]
testing = train_df.loc[train_df['year']>2019]
X_train = training[predictors]
y_train = training['top_10_masters']
X_test = testing[predictors]
y_test = testing['top_10_masters']

pipeline = Pipeline([
    ('smote', SMOTE()),
    #('under', RandomUnderSampler()),
    ('classifier', SVC())
])

param_grid = {
    'smote__sampling_strategy': [0.2, 0.75, 1.0],
    'smote__k_neighbors': [1, 3, 5],
    #'under__sampling_strategy': [0.3, 0.5, 0.8]
}

grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print('Best params:', grid_search.best_params_)

print('precision:', metrics.precision_score(y_test, y_pred))
print('recall:', metrics.recall_score(y_test, y_pred))
print('f1:', metrics.f1_score(y_test, y_pred))
print('accuracy:', metrics.accuracy_score(y_test, y_pred))

Fitting 5 folds for each of 9 candidates, totalling 45 fits
Best params: {'smote__k_neighbors': 1, 'smote__sampling_strategy': 1.0}
precision: 0.05673758865248227
recall: 1.0
f1: 0.10738255033557047
accuracy: 0.3051201671891327

In [18]:
training = train_df.loc[train_df['year']<=2019]
testing = train_df.loc[train_df['year']>2019]
X_train = training[predictors]
y_train = training['top_10_masters']
X_test = testing[predictors]
y_test = testing['top_10_masters']

over = SMOTE(sampling_strategy=0.2, k_neighbors=3)
under = RandomUnderSampler(sampling_strategy=0.7)

steps = [('o', over), ('u', under)]
pipeline = Pipeline(steps=steps)

X_train_res, y_train_res = pipeline.fit_resample(X_train, y_train)

model = SVC()
model.fit(X_train_res, y_train_res)

y_pred = model.predict(X_test)


print('precision:', metrics.precision_score(y_test, y_pred))
print('recall:', metrics.recall_score(y_test, y_pred))
print('f1:', metrics.f1_score(y_test, y_pred))
print('accuarcy:', metrics.accuracy_score(y_test, y_pred))

precision: 0.0
recall: 0.0
f1: 0.0
accuarcy: 0.9582027168234065

C:\Users\mrice\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [19]:
training = train_df.loc[train_df['year']<=2019]
testing = train_df.loc[train_df['year']>2019]
X_train = training[predictors]
y_train = training['masters_win']
X_test = testing[predictors]
y_test = testing['masters_win']

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

over = SMOTE(sampling_strategy=0.5, k_neighbors=5)
under = RandomUnderSampler(sampling_strategy=1)

steps = [('o', over), ('u', under)]
pipeline = Pipeline(steps=steps)

X_train_res, y_train_res = pipeline.fit_resample(X_train_std, y_train)

model = SVC(kernel='linear')
model.fit(X_train_res, y_train_res)

y_pred = model.predict(X_test_std)


print('precision:', metrics.precision_score(y_test, y_pred))
print('recall:', metrics.recall_score(y_test, y_pred))
print('f1:', metrics.f1_score(y_test, y_pred))
print('accuarcy:', metrics.accuracy_score(y_test, y_pred))

precision: 0.08333333333333333
recall: 0.75
f1: 0.15
accuarcy: 0.9644723092998955

In [20]:
data_2025=data_2025.dropna()

In [21]:
training = train_df
test = data_2025
X_train = training[predictors]
y_train = training['masters_win']
X_test = test[predictors]

# Scale the data (fit on training data, transform both training and testing data)
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
        
# Apply SMOTE and RandomUnderSampler to the training data only
over = SMOTE(sampling_strategy=0.2, k_neighbors= 3)
under = RandomUnderSampler(sampling_strategy = 0.5)

steps = [('o', over), ('u', under)]
pipeline = Pipeline(steps=steps)

X_train_mod, y_train_mod = pipeline.fit_resample(X_train_std, y_train)
        
# Train the model on the resampled training data
svc = SVC(kernel = 'linear', probability = True)
model = svc.fit(X_train_mod, y_train_mod)

y_pred = model.predict(X_test_std)
y_pred_proba = model.predict_proba(X_test_std)

#Add Predictions to DF
data_2025['masters_prediction'] = y_pred.tolist()
probs = []
for i in range(0, len(y_pred_proba)):
    prob = y_pred_proba[i,1]
    probs.append(prob)
    
data_2025['prob'] = probs

index = probs.index(np.max(probs))
loc = X_test.iloc[index,:]['avg_score']
data_2025.loc[data_2025['avg_score'] == loc]

,player_id,player_name,year,avg_score,bounce_back,drive_acc,drive_dist,gir,par3_score,par4_score,...,strokes_gained_arg,strokes_gained_atg,strokes_gained_ot,strokes_gained_putt,strokes_gained_ttg,top_10,1st_place_finishes,masters_finish,masters_prediction,prob
3408,33448,Justin Thomas,2024,70.2,18.82,55.83,309.1,65.59,3.0,4.0,...,0.466,0.639,0.135,-0.478,1.24,6.0,0.0,CUT,1,0.964042

In [22]:
winners = data_2025.loc[data_2025['masters_prediction']==1]
print(winners)

      player_id        player_name  year  avg_score  bounce_back  drive_acc  \
2646      28237       Rory McIlroy  2024     69.914        20.75      60.29
3408      33448      Justin Thomas  2024     70.200        18.82      55.83
3486      34046      Jordan Spieth  2024     70.844        18.45      62.45
4062      46046  Scottie Scheffler  2024     68.645        31.75      66.90
4237      48081  Xander Schauffele  2024     69.137        21.80      60.84

      drive_dist    gir  par3_score  par4_score  ...  strokes_gained_arg  \
2646       320.2  65.70        3.04        3.98  ...               0.248
3408       309.1  65.59        3.00        4.00  ...               0.466
3486       306.9  65.87        3.11        4.00  ...              -0.024
4062       303.8  73.16        2.98        3.88  ...               0.316
4237       308.5  69.97        2.92        3.92  ...               0.195

      strokes_gained_atg  strokes_gained_ot  strokes_gained_putt  \
2646               0.260              0.730                0.173
3408               0.639              0.135               -0.478
3486              -0.204              0.500               -0.006
4062               1.269              0.816                0.095
4237               0.678              0.557                0.510

      strokes_gained_ttg  top_10  1st_place_finishes  masters_finish  \
2646               1.239     7.0                 2.0             T22
3408               1.240     6.0                 0.0             CUT
3486               0.271     3.0                 0.0             CUT
4062               2.401    16.0                 7.0               1
4237               1.431    15.0                 2.0               8

      masters_prediction      prob
2646                   1  0.942603
3408                   1  0.964042
3486                   1  0.714560
4062                   1  0.875522
4237                   1  0.682098

[5 rows x 24 columns]

In [24]:
from tqdm import tqdm
from collections import Counter
import collections

dubs = []

for i in tqdm(range(0, 500), desc="Running simulations"):
    # Split Data
    training = train_df
    test = data_2025
    X_train = training[predictors]
    y_train = training['masters_win']
    X_test = test[predictors]

    # Standardize Predictors
    scaler = StandardScaler()
    X_train_std = scaler.fit_transform(X_train)
    X_test_std = scaler.fit_transform(X_test)

    # SMOTE and Undersampling
    over = SMOTE(sampling_strategy=0.2, k_neighbors=3)
    under = RandomUnderSampler(sampling_strategy=0.5)

    steps = [('o', over), ('u', under)]
    pipeline = Pipeline(steps=steps)

    X_train_mod, y_train_mod = pipeline.fit_resample(X_train_std, y_train)

    # Train Model
    svc = SVC(kernel='linear', probability=True)
    model = svc.fit(X_train_mod, y_train_mod)

    y_pred = model.predict(X_test_std)
    y_pred_proba = model.predict_proba(X_test_std)

    # Add Predictions to DF
    data_2025['masters_prediction'] = y_pred.tolist()
    data_2025['prob'] = [prob[1] for prob in y_pred_proba]

    winners = data_2025['player_name'].loc[data_2025['masters_prediction'] == 1].to_list()
    dubs.append(winners)

# Format Results
flat_list = [item for sublist in dubs for item in sublist]
results = Counter(flat_list)
sorted_results = collections.OrderedDict(sorted(results.items(), reverse=True, key=lambda t: t[1]))

Running simulations: 100%|██████████| 500/500 [05:32<00:00,  1.50it/s]

In [25]:
print(sorted_results)

OrderedDict([('Rory McIlroy', 500), ('Justin Thomas', 500), ('Scottie Scheffler', 500), ('Xander Schauffele', 500)])

In [ ]:
training = train_df
test = data_2025
X_train = training[predictors]
y_train = training['masters_win']
X_test = test[predictors]

# Scale the data (fit on training data, transform both training and testing data)
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
        
# Apply SMOTE and RandomUnderSampler to the training data only
over = SMOTE(sampling_strategy=0.2, k_neighbors= 3)
under = RandomUnderSampler(sampling_strategy = 0.5)

steps = [('o', over), ('u', under)]
pipeline = Pipeline(steps=steps)

X_train_mod, y_train_mod = pipeline.fit_resample(X_train_std, y_train)
        
# Train the model on the resampled training data
svc = SVC(kernel = 'linear', probability = True)
model = svc.fit(X_train_mod, y_train_mod)

y_pred = model.predict(X_test_std)
y_pred_proba = model.predict_proba(X_test_std)

#Add Predictions to DF
data_2025['masters_prediction'] = y_pred.tolist()
probs = []
for i in range(0, len(y_pred_proba)):
    prob = y_pred_proba[i,1]
    probs.append(prob)
    
data_2025['prob'] = probs

index = probs.index(np.max(probs))
loc = X_test.iloc[index,:]['avg_score']
data_2025.loc[data_2025['avg_score'] == loc]

C:\Users\mrice\AppData\Local\Temp\ipykernel_22716\635712107.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_2025['masters_prediction'] = y_pred.tolist()
C:\Users\mrice\AppData\Local\Temp\ipykernel_22716\635712107.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_2025['prob'] = probs

,player_id,player_name,year,avg_score,bounce_back,drive_acc,drive_dist,gir,par3_score,par4_score,...,strokes_gained_arg,strokes_gained_atg,strokes_gained_ot,strokes_gained_putt,strokes_gained_ttg,top_10,1st_place_finishes,masters_finish,masters_prediction,prob
3408,33448,Justin Thomas,2024,70.2,18.82,55.83,309.1,65.59,3.0,4.0,...,0.466,0.639,0.135,-0.478,1.24,6.0,0.0,CUT,1,0.934499